trigger: none

pr: none

variables:
- template: /Deployment/Variables/pipeline-vars-shared.yml
- name: devEnvironment
  value: Development
- name: testEnvironment
  value: Test
- name: prodEnvironment
  value: Production

resources:
  pipelines:
  - pipeline: cipipeline
    # TODO: Update with the name of your CI pipeline
    source: 'CI - ru-core-integrations-customer - logic app'
    trigger:
      branches:
      - master

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: /Deployment/Variables/pipeline-vars-dev.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@2
            displayName: 'Deploy logic app workflows'
            inputs:
              # TODO: Fill in with the name of your Azure service connection
              azureSubscription: 'RU-Core-Dev'
              appType: 'functionApp'
              appName: '$(logicAppName)'
              package: '$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip'
              deploymentMethod: 'runFromPackage'
              #deploymentMethod: 'zipDeploy'

# - stage: TEST
#   displayName: 'TEST Deployment'
#   variables:
#   - template: variables/pipeline-vars-test.yml
#   jobs:
#   - deployment: deploy_logicapp_resources
#     displayName: Deploy Logic App
#     pool:
#       vmImage: ubuntu-latest
#     environment: $(testEnvironment)
#     variables:
#       deploymentMode: 'Incremental'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: AzureFunctionApp@1
#             displayName: 'Deploy logic app workflows'
#             inputs:
#               # TODO: Fill in with the name of your Azure service connection
#               azureSubscription: 'No-Core-Test'
#               appType: 'functionApp'
#               appName: '$(logicAppName)'
#               package: '$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip'
#               deploymentMethod: 'runFromPackage'

# - stage: PROD
#   displayName: 'PROD Deployment'
#   variables:
#   - template: variables/pipeline-vars-prod.yml
#   jobs:
#   - deployment: deploy_logicapp_resources
#     displayName: Deploy Logic App
#     pool:
#       vmImage: ubuntu-latest
#     environment: $(prodEnvironment)
#     variables:
#       deploymentMode: 'Incremental'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: AzureFunctionApp@1
#             displayName: 'Deploy logic app workflows'
#             inputs:
#               # TODO: Fill in with the name of your Azure service connection
#               azureSubscription: 'No-Core-Prod'
#               appType: 'functionApp'
#               appName: '$(logicAppName)'
#               package: '$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip'
#               #deploymentMethod: 'runFromPackage'
#               deploymentMethod: 'zipDeploy'