trigger: none

pr: none

variables:
- template: /Deployment/Variables/pipeline-vars-shared.yml
- name: artifactName
  value: deploy_artifacts
- name: devEnvironment
  value: Development
- name: testEnvironment
  value: Test
- name: prodEnvironment
  value: Production

stages:
- stage: Builds
  displayName: 'Publish IaC Artifacts'
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        sourceFolder: 'Deployment'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: $(artifactName)
  
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: /Deployment/Variables/pipeline-vars-dev.yml
  jobs:
  - template: /Deployment/Infrastructure/LogicApp/logic-app-iac-template.yml
    parameters:
      environment: $(devEnvironment)
      # TODO: Fill in with the name of your Azure service connection
      serviceConnection: 'RU-Core-Dev'

# - stage: TEST
#   displayName: 'TEST Deployment'
#   variables:
#   - template: variables/pipeline-vars-test.yml
#   jobs:
#   - template: ../templates/logic-app-iac-template.yml
#     parameters:
#       environment: $(testEnvironment)
#       # TODO: Fill in with the name of your Azure service connection
#       serviceConnection: 'NO-Core-Test'

# - stage: PROD
#   displayName: 'PROD Deployment'
#   variables:
#   - template: variables/pipeline-vars-prod.yml
#   jobs:
#   - template: ../templates/logic-app-iac-template.yml
#     parameters:
#       environment: $(prodEnvironment)
#       # TODO: Fill in with the name of your Azure service connection
#       serviceConnection: 'NO-Core-Prod'