#nullable disable
using Newtonsoft.Json;

namespace ru.core.integrations.customer.core.Model.Dataverse;

public class AccountOdataResponseModel
{
    [JsonProperty("@odata.context")]
    public string odatacontext { get; set; }
    public List<AccountSingle> value { get; set; }
}

public class AccountSingle
{
    [JsonProperty("@odata.etag")]
    public string odataetag { get; set; }
    public string emailaddress3 { get; set; }
    public bool creditonhold { get; set; }
    public string _hbb_wholesaler_value { get; set; }
    public double exchangerate { get; set; }
    public string _territoryid_value { get; set; }
    public object hbb_delivery_obstruction_description { get; set; }
    public double? address1_latitude { get; set; }
    public double? creditlimit_base { get; set; }
    public object adx_createdbyipaddress { get; set; }
    public int customersizecode { get; set; }
    public object openrevenue_state { get; set; }
    public object _preferredsystemuserid_value { get; set; }
    public object hbb_alcohol_license_number { get; set; }
    public object address2_line3 { get; set; }
    public object _hbb_technician_value { get; set; }
    public object onholdtime { get; set; }
    public object openrevenue_base { get; set; }
    public object teamsfollowed { get; set; }
    public object address1_shippingmethodcode { get; set; }
    public object hbb_delivery_timeclose { get; set; }
    public string _msdyn_salestaxcode_value { get; set; }
    public string crc81_profil { get; set; }
    public string entityimage { get; set; }
    public object address2_primarycontactname { get; set; }
    public object _primarycontactid_value { get; set; }
    public object hbb_customernoref2 { get; set; }
    public string telephone1 { get; set; }
    public object hbb_licence_alc_fromdate { get; set; }
    public object address1_telephone2 { get; set; }
    public object address1_fax { get; set; }
    public string pp_alias { get; set; }
    public object customertypecode { get; set; }
    public int hbb_customer_saleschannel { get; set; }
    public object hbb_license_alcohol_name { get; set; }
    public object aging60_base { get; set; }
    public object hbb_openinghoursto { get; set; }
    public string address1_addressid { get; set; }
    public object revenue { get; set; }
    public int pp_workhoursthisyear_state { get; set; }
    public object yominame { get; set; }
    public object _modifiedbyexternalparty_value { get; set; }
    public bool donotbulkemail { get; set; }
    public object hbb_delivery_goods_placement { get; set; }
    public DateTime modifiedon { get; set; }
    public bool marketingonly { get; set; }
    public object hbb_tekniker { get; set; }
    public object new_antalltrappetarn { get; set; }
    public object _createdbyexternalparty_value { get; set; }
    public object address2_longitude { get; set; }
    public int accountratingcode { get; set; }
    public string address2_addressid { get; set; }
    public string hbb_bevilgningstype { get; set; }
    public object address2_country { get; set; }
    public int? paymenttermscode { get; set; }
    public string hbb_kundenummer { get; set; }
    public string address1_stateorprovince { get; set; }
    public object address1_primarycontactname { get; set; }
    public object new_tankolleveringsdag { get; set; }
    public object _pp_hovedaktivia_kunde_value { get; set; }
    public bool donotbulkpostalmail { get; set; }
    public object primarytwitterid { get; set; }
    public int businesstypecode { get; set; }
    public object _masterid_value { get; set; }
    public object _createdonbehalfby_value { get; set; }
    public object industrycode { get; set; }
    public object _preferredserviceid_value { get; set; }
    public double? address1_longitude { get; set; }
    public object _msdyn_billingaccount_value { get; set; }
    public int preferredcontactmethodcode { get; set; }
    public int hbb_type { get; set; }
    public string new_kolliordrefristklokkeslett { get; set; }
    public string hbb_gln { get; set; }
    public object _cr0c6_chainlevel4_value { get; set; }
    public object address2_telephone3 { get; set; }
    public object address2_telephone2 { get; set; }
    public bool merged { get; set; }
    public object hbb_delivery_goodreception_meters_distance { get; set; }
    public bool? msdyn_taxexempt { get; set; }
    public object utcconversiontimezonecode { get; set; }
    public bool? crc81_kundeportalikkeaktuell { get; set; }
    public DateTime? hbb_avtaletil { get; set; }
    public string hbb_sapkundenummer { get; set; }
    public object hbb_ifs_customer_number { get; set; }
    public object processid { get; set; }
    public object address1_country { get; set; }
    public object _msdyn_accountkpiid_value { get; set; }
    public object new_tanklleveringsdag { get; set; }
    public int? hbb_activity_space { get; set; }
    public string hbb_tradesolution_lopenummer { get; set; }
    public bool new_fritakfraktgebyr { get; set; }
    public DateTime? hbb_opening_date { get; set; }
    public object hbb_imageofcustomersmenu_url { get; set; }
    public object hbb_imageofcustomersmenuid { get; set; }
    public object address1_postofficebox { get; set; }
    public string _transactioncurrencyid_value { get; set; }
    public object msdyncrm_insights_placeholder { get; set; }
    public string address2_postalcode { get; set; }
    public object adx_modifiedbyipaddress { get; set; }
    public string address1_line1 { get; set; }
    public object hbb_hovedflaskel { get; set; }
    public string address1_composite { get; set; }
    public string _owningteam_value { get; set; }
    public string new_kundenummer { get; set; }
    public string _owningbusinessunit_value { get; set; }
    public object address2_latitude { get; set; }
    public object address2_postofficebox { get; set; }
    public object hbb_kategori { get; set; }
    public object address1_upszone { get; set; }
    public object hbb_leverandr { get; set; }
    public string name { get; set; }
    public DateTime createdon { get; set; }
    public object aging30 { get; set; }
    public string _createdby_value { get; set; }
    public object websiteurl { get; set; }
    public int? new_kategori { get; set; }
    public object accountcategorycode { get; set; }
    public object ftpsiteurl { get; set; }
    public object stageid { get; set; }
    public string telephone2 { get; set; }
    public object hbb_imageofcustomersmenu_timestamp { get; set; }
    public int address2_addresstypecode { get; set; }
    public object msdyn_taxexemptnumber { get; set; }
    public string address1_postalcode { get; set; }
    public object pp_workordernotes { get; set; }
    public object new_calcbeskrivelsetankollevdag { get; set; }
    public object address1_line2 { get; set; }
    public object hbb_opprettbetillingogordre { get; set; }
    public bool new_aktiver_brukere_til_kundeportal { get; set; }
    public object pp_forrigerens { get; set; }
    public int? msevtmgt_hotelgroup { get; set; }
    public object address1_telephone3 { get; set; }
    public bool participatesinworkflow { get; set; }
    public object tickersymbol { get; set; }
    public string new_hansacrm { get; set; }
    public object address2_upszone { get; set; }
    public object address1_telephone1 { get; set; }
    public object msdyn_primarytimezone { get; set; }
    public object _hbb_driftsingenior_value { get; set; }
    public object _slaid_value { get; set; }
    public object adx_modifiedbyusername { get; set; }
    public bool new_erdeltfelleskunde { get; set; }
    public object hbb_delivery_place_image_url { get; set; }
    public object pp_telefontekniker { get; set; }
    public int accountclassificationcode { get; set; }
    public object marketcap { get; set; }
    public bool donotemail { get; set; }
    public object hbb_delivery_timeopen { get; set; }
    public DateTime pp_workhoursthisyear_date { get; set; }
    public object new_tankolordrefristklokkeslett { get; set; }
    public string accountnumber { get; set; }
    public object aging90 { get; set; }
    public object address1_utcoffset { get; set; }
    public int statecode { get; set; }
    public bool? msdyn_gdproptout { get; set; }
    public string _ownerid_value { get; set; }
    public string address2_composite { get; set; }
    public object msdyn_workorderinstructions { get; set; }
    public string address1_city { get; set; }
    public object overriddencreatedon { get; set; }
    public string hbb_betalingsbetingelser { get; set; }
    public object pp_cleaninginterval { get; set; }
    public string _cr0c6_chainlevel1_value { get; set; }
    public string _cr0c6_chainlevel2_value { get; set; }
    public object hbb_delivery_place_image { get; set; }
    public string new_leveringsdagkolli { get; set; }
    public object hbb_openinghoursfrom { get; set; }
    public object new_andelvaretappetarn { get; set; }
    public string address2_line1 { get; set; }
    public int? crc81_produl { get; set; }
    public long? entityimage_timestamp { get; set; }
    public string crc81_chainlevel { get; set; }
    public bool donotsendmm { get; set; }
    public int hbb_fase { get; set; }
    public string address1_county { get; set; }
    public string cr0c6_customers_customernumber { get; set; }
    public object hbb_delivery_rolling_goods { get; set; }
    public string description { get; set; }
    public object _msdyn_serviceterritory_value { get; set; }
    public object hbb_hovedlptapp { get; set; }
    public bool hbb_kjede { get; set; }
    public object primarysatoriid { get; set; }
    public object fax { get; set; }
    public string hbb_organisasjonsnummer { get; set; }
    public bool hbb_prospect { get; set; }
    public object _msdyn_salesaccelerationinsightid_value { get; set; }
    public string _modifiedby_value { get; set; }
    public object adx_createdbyusername { get; set; }
    public int shippingmethodcode { get; set; }
    public object new_omsetningiliter { get; set; }
    public string emailaddress2 { get; set; }
    public object lastonholdtime { get; set; }
    public int? hbb_omsetning { get; set; }
    public object sharesoutstanding { get; set; }
    public object cr0c6_assortmentcode { get; set; }
    public object address2_fax { get; set; }
    public string emailaddress1 { get; set; }
    public object preferredappointmenttimecode { get; set; }
    public object hbb_delivery_place_imageid { get; set; }
    public object hbb_hovedflaskel2 { get; set; }
    public int? msevtmgt_rentalcarprovider { get; set; }
    public int versionnumber { get; set; }
    public object hbb_license_alcohol { get; set; }
    public object preferredappointmentdaycode { get; set; }
    public int? cr0c6_warehouse { get; set; }
    public object aging90_base { get; set; }
    public string address2_city { get; set; }
    public object hbb_invoice_mail { get; set; }
    public string _cr0c6_chainarea_value { get; set; }
    public object _hbb_sapcustomercreatedtriggeredby_value { get; set; }
    public string address2_line2 { get; set; }
    public string address2_county { get; set; }
    public object hbb_svinn { get; set; }
    public object opendeals_state { get; set; }
    public double? creditlimit { get; set; }
    public object _hbb_owner_2_value { get; set; }
    public bool? hbb_opprettbestilling { get; set; }
    public DateTime? hbb_avtalefra { get; set; }
    public string address1_name { get; set; }
    public object hbb_urlforcustomersmenu { get; set; }
    public object revenue_base { get; set; }
    public object ownershipcode { get; set; }
    public object hbb_email_servicereport { get; set; }
    public string _owninguser_value { get; set; }
    public double? hbb_segment_assortment_score { get; set; }
    public int territorycode { get; set; }
    public object new_tankolordrefristtimer { get; set; }
    public object sic { get; set; }
    public object new_leveringsdagkolliukefrekvens { get; set; }
    public object new_channel { get; set; }
    public string hbb_leveringsfrekvens { get; set; }
    public object lastusedincampaign { get; set; }
    public object _defaultpricelevelid_value { get; set; }
    public object importsequencenumber { get; set; }
    public int? hbb_fjorretsomsetningiliter { get; set; }
    public object _msdyn_preferredresource_value { get; set; }
    public object _modifiedonbehalfby_value { get; set; }
    public bool new_kundeportalaktivert { get; set; }
    public string hbb_legal_name { get; set; }
    public object hbb_delivery_place_image_timestamp { get; set; }
    public object hbb_serviceansvarlig { get; set; }
    public bool donotpostalmail { get; set; }
    public object hbb_grossistmodul_customernumber { get; set; }
    public object _msdyn_workhourtemplate_value { get; set; }
    public object marketcap_base { get; set; }
    public string entityimage_url { get; set; }
    public string hbb_kundetype { get; set; }
    public object numberofemployees { get; set; }
    public object aging60 { get; set; }
    public bool followemail { get; set; }
    public object msdyn_travelcharge_base { get; set; }
    public object aging30_base { get; set; }
    public object _preferredequipmentid_value { get; set; }
    public object hbb_messagetodriver { get; set; }
    public object stockexchange { get; set; }
    public object address1_freighttermscode { get; set; }
    public object _hbb_customer_segment_value { get; set; }
    public object _hbb_alcohol_license_type_value { get; set; }
    public string hbb_kommune { get; set; }
    public string _cr0c6_chainlevel3_value { get; set; }
    public string address2_name { get; set; }
    public object address1_line3 { get; set; }
    public object address2_telephone1 { get; set; }
    public object hbb_delivery_parking { get; set; }
    public bool donotfax { get; set; }
    public int address2_shippingmethodcode { get; set; }
    public int? timezoneruleversionnumber { get; set; }
    public object hbb_hovedflaskel1 { get; set; }
    public bool new_tankolautofyll { get; set; }
    public object timespentbymeonemailandmeetings { get; set; }
    public object new_andelvarekjoleskap { get; set; }
    public object _msa_managingpartnerid_value { get; set; }
    public int? new_kolliordrefristtimer { get; set; }
    public object opendeals { get; set; }
    public object hbb_imageofcustomersmenu { get; set; }
    public object hbb_member_number { get; set; }
    public int? msdyn_travelchargetype { get; set; }
    public DateTime opendeals_date { get; set; }
    public object _msdyn_segmentid_value { get; set; }
    public DateTime? hbb_closing_date { get; set; }
    public bool new_tankolkunde { get; set; }
    public object hbb_delivery_assistive_devices { get; set; }
    public bool donotphone { get; set; }
    public string _hbb_assortment_code_value { get; set; }
    public object hbb_tradesolution_extra_info { get; set; }
    public object telephone3 { get; set; }
    public DateTime openrevenue_date { get; set; }
    public int? hbb_kredittgrense { get; set; }
    public string _new_austmannselger_value { get; set; }
    public int statuscode { get; set; }
    public object address2_utcoffset { get; set; }
    public string _parentaccountid_value { get; set; }
    public object new_antallkjoleskap { get; set; }
    public object openrevenue { get; set; }
    public int? new_kilde { get; set; }
    public object _slainvokedid_value { get; set; }
    public object msdyn_travelcharge { get; set; }
    public object address1_addresstypecode { get; set; }
    public object new_sharepointurl { get; set; }
    public object _originatingleadid_value { get; set; }
    public string accountid { get; set; }
    public object traversedpath { get; set; }
    public int address2_freighttermscode { get; set; }
    public double pp_workhoursthisyear { get; set; }
    public object new_new_tankolleveringsdag { get; set; }
    public object hbb_licence_alc_todate { get; set; }
    public object address2_stateorprovince { get; set; }
    public object crc81_storrelse { get; set; }
    public object hbb_sales_area_square_meters { get; set; }
    public string entityimageid { get; set; }
    public DateTime? hbb_sistebestilling { get; set; }
}

