#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ru.core.integrations.customer.core.Model.Dataverse
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum rub_country
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Denmark = 915030000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		France = 915030001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Finland = 915030002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sweden = 915030003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Norway = 915030004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Estonia = 915030005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letvia = 915030006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lithuania = 915030007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Netherlands = 915030008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Belgium = 915030009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Italy = 915030010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canada = 915030011,
	}
}
#pragma warning restore CS1591
