#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ru.core.integrations.customer.core.Model.Dataverse
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum rub_accounttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PointofSale = 915030000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enterprise = 915030001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Distributor = 915030002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Vendor = 915030003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prospect = 915030004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customer = 915030005,
	}
}
#pragma warning restore CS1591
