#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ru.core.integrations.customer.core.Model.Dataverse
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum rub_outdoor
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel915030000 = 915030000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel915030001 = 915030001,
	}
}
#pragma warning restore CS1591
