parameters:
- name: serviceConnection
  type: string
- name: devopsEnvironment
  type: string


jobs:
- deployment: Deploy
  displayName: Deploy function app
  environment: ${{ parameters.devopsEnvironment }}

  strategy:
   runOnce:
     deploy:
       steps:
        - task: AzureFunctionApp@2
          displayName: "Function app deploy"
          inputs:
            connectedServiceNameARM: ${{ parameters.serviceConnection }}
            appType: 'functionApp'
            appName: '$(functionAppName)'
            package: '$(Agent.BuildDirectory)/cd-pipeline/drop/**/*.zip'
            runtimeStack: 'DOTNET-ISOLATED|9.0'
            deploymentMethod: 'runFromPackage'

      #  - task: AzureRmWebAppDeployment@4
      #    displayName: "Azure app service deploy"
      #    inputs:
      #      azureSubscription: ${{ parameters.serviceConnection }}
      #      WebAppName: '$(functionAppName)'
      #      deploymentMethod: 'zipDeploy'
      #      appType: webAppLinux
      #      package: '$(Agent.BuildDirectory)/cd-pipeline/drop/**/*.zip'
